import {ArrowRight,CalendarDays,Compass,Heart,Menu,Search,Sparkles,Users,WandSparkles} from "lucide-react";
import {homepageExperiences as bookable,inventoryUrl} from "./data/travel-inventory";
const destinations=[
 {slug:"bali",name:"Bali",detail:"Island rituals & hidden valleys",image:"/images/destination-bali.png"},
 {slug:"yogyakarta",name:"Yogyakarta",detail:"Ancient arts & living heritage",image:"/images/destination-yogyakarta.png"},
 {slug:"lombok",name:"Lombok",detail:"Wild coastlines & Sasak culture",image:"/images/destination-lombok.png"},
 {slug:"flores",name:"Flores",detail:"Volcanic lakes & village stories",image:"/images/destination-flores.png"}];
const stays=[
 {place:"Bali",type:"For rice-field stillness",name:"Browse stays in Bali",price:"Check latest price",image:"/images/stay-sidemen.png",sourceUrl:"https://www.traveloka.com/id-id/hotel/indonesia/region/bali-102746",affiliateUrl:null},
 {place:"Yogyakarta",type:"For art and old Java",name:"Browse stays in Yogyakarta",price:"Check latest price",image:"/images/stay-yogyakarta.png",sourceUrl:"https://www.traveloka.com/en-id/hotel",affiliateUrl:null},
 {place:"Lombok",type:"For barefoot coastlines",name:"Browse stays in Lombok",price:"Check latest price",image:"/images/stay-lombok.png",sourceUrl:"https://www.traveloka.com/en-id/hotel",affiliateUrl:null},
 {place:"Labuan Bajo",type:"For island horizons",name:"Browse stays in Labuan Bajo",price:"Check latest price",image:"/images/stay-labuan-bajo.png",sourceUrl:"https://www.traveloka.com/en-id/hotel",affiliateUrl:null}];
function Logo({light=false}:{light?:boolean}){return <a className={`logo ${light?"text-white":"text-forest"}`} href="/"><span className="logo-mark">IE</span><span>IndoEthno</span></a>}
function SectionHead({eyebrow,title,link,href}:{eyebrow:string,title:string,link:string,href:string}){return <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><a className="text-link" href={href}>{link}<ArrowRight size={17}/></a></div>}
export default function Home(){return <main>
 <section className="hero"><nav><Logo light/><div className="navlinks"><a href="#destinations">Destinations</a><a href="#popular">Things to Do</a><a href="#stays">Hotels</a><a href="#book">Experiences</a><a href="#planner">Trip Planner</a><a href="#discover">Discover</a></div><div className="nav-actions"><button className="saved"><Heart size={18}/> Saved</button><a className="nav-cta" href="#planner">Plan a trip <ArrowRight size={16}/></a><button className="menu" aria-label="Menu"><Menu/></button></div></nav><div className="hero-content"><p className="hero-kicker"><span/>TRAVEL DEEPER INTO INDONESIA</p><h1>Discover the<br/><em>Real Indonesia</em></h1><p className="hero-copy">Culture, flavour, wilderness, and the people who bring it all to life. Discover a journey shaped around what moves you.</p><a className="primary-cta" href="#planner">Plan My Trip <ArrowRight size={18}/></a></div><p className="photo-note">Jatiluwih, Bali <span>08°22′S 115°08′E</span></p></section>
 <section className="planner-wrap" id="planner"><div className="planner-intro"><Sparkles size={20}/><div><b>Where will Indonesia take you?</b><span>Tell us what you’re drawn to. We’ll shape the rest.</span></div></div><form className="planner"><label><small>WHERE</small><span><Search size={18}/> Choose a destination</span></label><label><small>WHEN</small><span><CalendarDays size={18}/> Add dates</span></label><label><small>TRAVELLERS</small><span><Users size={18}/> 2 guests</span></label><button type="button"><WandSparkles size={18}/> Create my journey</button></form></section>
<section className="section popular" id="popular"><SectionHead eyebrow="POPULAR RIGHT NOW" title="What curious travellers are finding" link="Plan a journey" href="#planner"/><div className="popular-grid"><a href="#planner" className="popular-lead"><img src="/images/popular-labuan-bajo.png" alt="Local boat captain sailing near Labuan Bajo"/><div className="shade"/><span className="trend-pill">MOST SAVED THIS WEEK</span><div><p>4 DAYS · FLORES</p><h3>Labuan Bajo beyond the dragons</h3><span>Slow boats, empty coves, and the wild edge of Indonesia.</span></div></a><div className="popular-list">{[["01","A first-timer’s guide to Yogyakarta","ARTS · FOOD · HISTORY","6 min read"],["02","Three days in Ubud, without rushing","CULTURE · NATURE","8 min read"],["03","Where Lombok still feels wonderfully quiet","BEACHES · VILLAGES","5 min read"]].map(x=><a href="#planner" key={x[0]}><span>{x[0]}</span><div><p>{x[2]}</p><h3>{x[1]}</h3></div><small>{x[3]} <ArrowRight size={15}/></small></a>)}</div></div></section>
 <section className="section destinations" id="destinations"><SectionHead eyebrow="EXPLORE THE ARCHIPELAGO" title="Four places to begin" link="Explore Bali" href="/bali"/><div className="destination-grid">{destinations.map((d,i)=><a href={d.slug==="bali"?"/bali":"#planner"} className={`destination-card card-${i}`} key={d.name}><img src={d.image} alt={d.name}/><div className="shade"/><div className="card-copy"><span>0{i+1}</span><h3>{d.name}</h3><p>{d.detail}</p></div><i><ArrowRight size={18}/></i></a>)}</div></section>
 <section className="section booking-section" id="book"><SectionHead eyebrow="TOP EXPERIENCES TO BOOK" title="Remarkable days, hosted locally" link="Browse all experiences" href="/bali#things-to-do"/><p className="section-deck">Chosen for the story they tell, the people you’ll meet, and the memories that linger well beyond the journey.</p><div className="booking-grid">{bookable.map(x=><article className="booking-card" key={x.productName}><div className="booking-image"><img src={x.image} alt={x.editorialTitle}/><button aria-label="Save experience"><Heart size={18}/></button></div><div className="booking-body"><p className="tag">{x.location}</p><h3>{x.editorialTitle}</h3><p className="description">{x.description}</p><div className="booking-meta"><span className="rating">TRAVELOKA</span><span><small>{x.priceLabel}</small></span></div><a className="outline-button" href={inventoryUrl(x)} rel="sponsored" data-item-name={x.productName} data-destination="Bali" data-cta-label="Check availability">Check availability <ArrowRight size={15}/></a></div></article>)}</div><p className="affiliate-note">Handpicked by IndoEthno · Booking links open with our trusted travel partners</p></section>
 <section className="journeys"><div className="journey-image indonesia"/><div className="journey-copy"><p className="eyebrow">TRAVEL, BEAUTIFULLY CONSIDERED</p><h2>Journeys with<br/>room to <em>wander</em></h2><p>Thoughtfully paced itineraries that bring together iconic landscapes, intimate encounters, and the freedom to follow your curiosity.</p><div className="route"><span>12 DAYS</span><b>Bali to Flores: Across the Lesser Sundas</b><div><i>Ubud</i><i>Sidemen</i><i>Lombok</i><i>Komodo</i></div></div><a className="primary-cta dark" href="#planner">Explore itineraries <ArrowRight size={18}/></a></div></section>
 <section className="section stay-section" id="stays"><SectionHead eyebrow="WHERE TO STAY" title="A good place changes the journey" link="Explore all stays" href="/bali#stays"/><div className="stay-grid">{stays.map((x,i)=><a className="stay-card" href={inventoryUrl(x)} rel="sponsored" data-item-name={x.name} data-destination={x.place} data-cta-label="View latest price" key={x.place}><div className="stay-image"><img src={x.image} alt={`Where to stay in ${x.place}`}/><span>0{i+1}</span></div><p>{x.type}</p><h3>{x.name}</h3><div><b>{x.place}</b><span>{x.price}</span><ArrowRight size={16}/></div></a>)}</div></section>
 <section className="section why" id="discover"><div className="why-title"><p className="eyebrow">WHY INDOETHNO</p><h2>Indonesia is more than<br/>a place. <em>Feel it.</em></h2></div><div className="principles">{[[Compass,"Discover beyond the obvious","We look past the familiar to reveal the stories, places, and people that make each island singular."],[WandSparkles,"Plan around what moves you","Our intelligence combines your travel style with deep local knowledge to shape a journey that feels yours."],[ArrowRight,"Book with quiet confidence","When you are ready, continue to carefully selected stays and experiences from trusted travel partners."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Compass;return <article key={String(title)}><span>0{i+1}</span><I size={27}/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></section>
<footer><div className="footer-top"><div><Logo light/><p>Travel deeper into the world’s<br/>most extraordinary archipelago.</p></div><div className="footer-links"><div><b>EXPLORE</b><a href="#destinations">Destinations</a><a href="#book">Experiences</a><a href="#stays">Hotels</a></div><div><b>PLAN</b><a href="#planner">Trip planner</a><a href="/bali#itinerary">Itineraries</a><a href="/affiliate-disclosure">Travel responsibly</a></div><div><b>INDOETHNO</b><a href="/about">About</a><a href="/contact">Contact</a><a href="/affiliate-disclosure">Affiliate disclosure</a></div></div><div className="newsletter"><b>LET INDONESIA FIND YOU</b><p>Stories, places, and journeys worth making.</p><label><input placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight/></button></label></div></div><div className="footer-bottom"><span>© 2026 IndoEthno</span><span>Born in Indonesia · Made for the curious</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></footer>
 </main>}
