import type {Metadata} from "next";
import {ArrowLeft,ArrowRight,Car,Clock,Compass,Heart,MapPin,Menu,Plane,Route} from "lucide-react";
import {baliActivities as activities,baliStayAreas as stays,baliTransport,inventoryUrl} from "../data/travel-inventory";
import "./bali.css";

export const metadata:Metadata={
title:{absolute:"Bali Beyond the Obvious — Things to Do, Stays & Itinerary | IndoEthno"},
  description:"Discover meaningful things to do in Bali, cultural experiences, where to stay, transport options, and a thoughtfully paced three-day itinerary.",
  alternates:{canonical:"/bali"},
  openGraph:{title:"Bali, beyond the obvious | IndoEthno",description:"A considered guide to Bali’s culture, landscapes, stays, and bookable experiences.",type:"website"}
};

const cultures=[
 ["01","Balinese cooking","Understand the island through spice, technique, and a hands-on class in Ubud.",inventoryUrl(activities[0])],
 ["02","GWK Cultural Park","See monumental Balinese art and scheduled cultural performances in Ungasan.",inventoryUrl(activities[2])],
 ["03","Traditional dance","See the Ramayana translated into chorus, movement, and firelight at Uluwatu.",inventoryUrl(activities[3])],
 ["04","Sacred forest","Walk among historic temples and resident macaques in Ubud’s forest sanctuary.",inventoryUrl(activities[4])],
 ["05","Bali cultural experiences","Browse currently available classes, culture, and tours across Bali.","https://www.traveloka.com/en-id/activities/indonesia/region/bali-102746"],
];

function Logo(){return <a className="logo" href="/"><span className="logo-mark">IE</span><span>IndoEthno</span></a>}
function Head({eyebrow,title}:{eyebrow:string,title:string}){return <div className="bali-head"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>}
function Footer(){return <footer><div className="footer-top"><div><a className="logo text-white" href="/"><span className="logo-mark">IE</span><span>IndoEthno</span></a><p>Travel deeper into the world’s<br/>most extraordinary archipelago.</p></div><div className="footer-links"><div><b>EXPLORE</b><a href="/#destinations">Destinations</a><a href="#things-to-do">Experiences</a><a href="#stays">Hotels</a></div><div><b>PLAN</b><a href="/#planner">Trip planner</a><a href="#itinerary">Itineraries</a><a href="#culture">Travel responsibly</a></div><div><b>DISCOVER</b><a href="/about">About</a><a href="/contact">Contact</a><a href="/affiliate-disclosure">Affiliate disclosure</a></div></div><div className="newsletter"><b>LET INDONESIA FIND YOU</b><p>Stories, places, and journeys worth making.</p><label><input placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight/></button></label></div></div><div className="footer-bottom"><span>© 2026 IndoEthno</span><span>Born in Indonesia · Made for the curious</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div></footer>}

export default function BaliPage(){const schema={"@context":"https://schema.org","@type":"TouristDestination",name:"Bali",description:metadata.description,url:"https://indoethno.com/bali",touristType:["Cultural travel","Nature travel","Food travel"]};return <main className="bali-page">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <nav className="bali-nav"><Logo/><div className="navlinks"><a href="/#destinations">Destinations</a><a href="#things-to-do">Things to Do</a><a href="#stays">Hotels</a><a href="#culture">Experiences</a><a href="/#planner">Trip Planner</a><a href="#itinerary">Discover</a></div><a className="nav-cta dark" href="/#planner">Plan a trip <ArrowRight size={16}/></a><button className="menu" aria-label="Menu"><Menu/></button></nav>
 <header className="bali-hero"><img src="/images/destination-bali.png" alt="Rice terraces and subak landscape in Bali"/><div className="shade"/><a className="back-link" href="/"><ArrowLeft size={15}/> INDONESIA</a><div className="bali-hero-copy"><p className="hero-kicker"><span/>THE ISLAND OF THE GODS</p><h1>Bali, beyond<br/><em>the obvious</em></h1><p>Look past the familiar and discover an island shaped by ritual, water, craft, and community—where every landscape carries a story.</p><div><span>BEST FOR</span><b>Culture · Food · Nature · Coast</b></div></div><p className="photo-note">Jatiluwih, Tabanan <span>08°22′S 115°08′E</span></p></header>

 <section className="bali-section activity-section" id="things-to-do"><Head eyebrow="THINGS TO DO IN BALI" title="Eight ways into the island"/><p className="bali-deck">Experiences selected for a stronger sense of place—not simply another box to tick.</p><div className="activity-grid">{activities.map((x,i)=><article className="bali-activity" key={x.productName}><div className="bali-card-image"><img src={x.image} alt={x.editorialTitle}/><span>0{i+1}</span><button aria-label={`Save ${x.editorialTitle}`}><Heart size={17}/></button></div><div className="bali-card-body"><p className="tag"><MapPin size={12}/>{x.location}</p><h3>{x.editorialTitle}</h3><p className="desc">{x.description}</p><div className="bali-meta"><span>TRAVELOKA</span><b>{x.priceLabel}</b></div><a className="outline-button" href={inventoryUrl(x)} rel="sponsored" data-item-name={x.productName} data-destination="Bali" data-cta-label="Check availability">Check availability <ArrowRight size={15}/></a></div></article>)}</div><p className="affiliate-note">Handpicked by IndoEthno · Booking links open with trusted travel partners</p></section>

 <section className="culture-section" id="culture"><div><p className="eyebrow">CULTURAL EXPERIENCES</p><h2>Meet the Bali that<br/><em>lives between places</em></h2><p>Culture here is not a performance staged for visitors. It is present in the offerings laid each morning, the materials shaped by hand, and the calendar of a village.</p></div><div className="culture-list">{cultures.map(x=><a href={x[3]} rel="sponsored" data-item-name={String(x[1])} data-destination="Bali" data-cta-label={String(x[1])} key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><ArrowRight size={18}/></a>)}</div></section>

 <section className="bali-section stay-section" id="stays"><Head eyebrow="WHERE TO STAY" title="Choose the rhythm that suits you"/><div className="bali-stay-grid">{stays.map((x,i)=><article className="bali-stay" key={x.productName}><div className="bali-stay-image"><img src={x.image} alt={`Places to stay in ${x.place}, Bali`}/><span>0{i+1}</span></div><p>{x.note}</p><h3>{x.place}</h3><p className="stay-desc">{x.description}</p><a href={inventoryUrl(x)} rel="sponsored" data-item-name={x.productName} data-destination={x.place??"Bali"} data-cta-label="View latest price">View latest price <ArrowRight size={16}/></a></article>)}</div></section>

 <section className="transport-section" id="getting-around"><div className="transport-intro"><p className="eyebrow">GETTING AROUND</p><h2>Move through Bali<br/>with less friction</h2><p>Distances on the map can be deceptive. Choose the right transport for your arrival, your day, and the roads between.</p></div><div className="transport-grid">{baliTransport.map((x,i)=>{const Icons=[Plane,Car,Route];const I=Icons[i];return <article key={x.productName}><span>0{i+1}</span><I size={27}/><h3>{x.title}</h3><p>{x.description}</p><a href={inventoryUrl(x)} rel="sponsored" data-item-name={x.productName} data-destination="Bali" data-cta-label="View latest price">View latest price <ArrowRight size={15}/></a></article>})}</div></section>

 <section className="bali-section itinerary-section" id="itinerary"><Head eyebrow="A SUGGESTED 3-DAY ITINERARY" title="Three days, thoughtfully paced"/><div className="itinerary-grid">{[["DAY 1","Ubud, through culture","Follow a verified full-day Ubud route through Tirta Empul, Monkey Forest, and Tegalalang Rice Terrace.","Tirta Empul · Monkey Forest · Tegalalang",inventoryUrl(activities[0])],["DAY 2","Volcano and cultural landmark","Start before dawn on Mount Batur, pause over breakfast in Kintamani, then continue south to GWK Cultural Park.","Mount Batur · Kintamani · GWK",inventoryUrl(activities[1])],["DAY 3","Cliffs and kecak","Travel to the Bukit Peninsula for Uluwatu’s clifftop temple and an evening Kecak Fire Dance performance.","Uluwatu · Temple · Kecak",inventoryUrl(activities[3])]].map((x,i)=><article key={x[0]}><span className="day-number">0{i+1}</span><p className="tag">{x[0]}</p><h3>{x[1]}</h3><p>{x[2]}</p><div><Clock size={14}/>{x[3]}</div><a className="outline-button" href={x[4]} rel="sponsored" data-item-name={String(x[1])} data-destination="Bali" data-cta-label="Check availability">Check availability <ArrowRight size={15}/></a></article>)}</div></section>
 <aside className="bali-plan"><Compass size={27}/><div><p className="eyebrow">MAKE IT YOURS</p><h2>Build a Bali journey around what moves you.</h2></div><a className="primary-cta dark" href="/#planner">Plan My Trip <ArrowRight size={17}/></a></aside>
 <Footer/>
 </main>}
